### ISSUE TITLE
Enable the new error messages for the libmamba solver option

### ISSUE THREAD

**Issue by syslaila** [conda/conda-libmamba-solver#102]
### Checklist

- [X] I added a descriptive title
- [X] I searched open requests and couldn't find a duplicate

### What is the idea?

Conda allows using the libmamba experimental solver. Mamba recently added new error messages (see https://medium.com/@AntoineProuvost/managing-conflicts-with-mamba-6a5fa10ed6a) that show the full dependency tree and the reason for failures. 
The new error messages can be enabled setting the `experimental_sat_error_message: true` in `.condarc`.

### Why is this needed?

The users will get an easy to understand error message - getting the full dependency tree and the reason for incompatibility.

### What should happen?

A user will add `experimental_sat_error_message: true` in `.condarc`.
When they get an error message from conda, they will see both the old error message & the new experimental error message.

**Comment by jaimergp** [comment]
While this is available on `micromamba`, the Python bindings for libmamba do not yet expose the `Context.experimental_sat_error_message` attribute, so we can't enable them yet :(

```bash
$ conda list libmambapy
libmambapy                1.1.0            py39hf0aba66_3    conda-forge
$ python -c "from libmambapy import Context; print(Context().experimental_sat_error_message)"
AttributeError: 'libmambapy.bindings.Context' object has no attribute 'experimental_sat_error_message'
```

Work being done on #103 if you want to track progress!

**Comment by costrouc** [comment]
Thanks for creating this issue @syslaila and letting us know that it is know available. I'm work on getting this added this week.

**Comment by jezdez** [comment]
FWIW libmamba 1.3.1 and libmambapy 1.3.1 were released on defaults.
