### ISSUE TITLE
Anaconda channels being fetched in addition to channels defined in .condarc 

### ISSUE THREAD

**Issue by andreostrovsky** [conda/conda-libmamba-solver#108]
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### What happened?

When using `solver: libmamba`, conda fetches repodata for Anaconda.org channels whenever solving the environment:
```
pkgs/r/win-64
pkgs/msys2/noarch
pkgs/main/noarch
pkgs/msys2/win-64
pkgs/r/noarch
pkgs/main/win-64
```
despite these channels not being configured anywhere. My .condarc explicitly only lists conda-forge, accessed through my organization's jfrog artifactory. 
When using the classic solver, conda respects this. As does mamba. Yet when using the libmamba solver, it ignores this and pulls repodata for these channels regardless.
This is a security issue, as I do not want connections made to any sources outside my organization, and have explicitly configured conda as such.

I have verified: 
- In `prefix/pkgs/cache` the Anaconda.org channel repodata is in fact being downloaded.
- There are no packages installed in the environment from any of these channels.
- There is no mention of any of these channels in `prefix/pkgs/urls.txt`
- There is no mention of any of these channels in `prefix/conda-meta/history`
- I have run `conda clean --all`

### Conda Info

```shell
    active environment : base
   active env location : C:\Users\xxx\prefix
           shell level : 0
      user config file : C:\Users\xxx\.condarc
populated config files : C:\Users\xxx\.condarc
         conda version : 22.11.1
   conda-build version : not installed
        python version : 3.9.13.final.0
      virtual packages : __archspec=1=x86_64
                         __win=0=0
      base environment : C:\Users\xxx\prefix   (writable)
     conda av data dir : C:\Users\xxx\prefix\etc\conda
 conda av metadata url : None
          channel URLs : https://xxx:yyy@zzz/api/conda/remote-conda-forge-public/win-64
                         https://xxx:yyy@zzz/api/conda/remote-conda-forge-public/noarch
         package cache : C:\Users\xxx\prefix\pkgs
                         C:\Users\xxx\.conda\pkgs
                         C:\Users\xxx\AppData\local\conda\conda\pkgs
      envs directories : C:\Users\xxx\prefix\envs
                         C:\Users\xxx\.conda\envs
                         C:\Users\xxx\AppData\local\conda\conda\envs
              platform : win-64
            user-agent : conda/22.11.1 requests/2.28.1 CPython/3.9.13 Windows/10 Windows/10.0.19044
         administrator : False
            netrc file : None
          offline mode : False
```

### Conda Config

```shell
==> C:\Users\xxx\.condarc <==
ssl_verify: False
channel_alias: https://xxx:yyy@zzz/api/conda/
channels:
  - remote-conda-forge-public
show_channel_urls: False
solver: libmamba
```

### Conda list

```shell
I cannot provide this due to the organization's security policies. The conda info and config above was typed out manually. 
Since I can't type out the entire package list, here are some relevant ones:
conda                   22.11.1   py39hcbf5309_1
conda-libmamba-solver   22.12.0   pyhd8ed1ab_0
libmamba                1.1.0     hd18bbca_2
libmambapy              1.1.0     py39h608c70e_2
mamba                   1.1.0     py39hca8391b_2
python                  3.9.13    hcf16a7b_0_cpython
```

**Comment by costrouc** [comment]
Hey @andreostrovsky I'm going to look at this issue and first see that I can reproduce this.

**Comment by costrouc** [comment]
I could not reproduce this issue with the docker image for development. Will try out a normal install and see if I run into the issue described here.

Steps I did:
  - `printf "channels: ['conda-forge']\nsolver: libmamba\n" > ~/.condarc`

My conda info after this step

```shell
     active environment : base
    active env location : /opt/conda
            shell level : 1
       user config file : /home/test_user/.condarc
 populated config files : /home/test_user/.condarc
          conda version : 23.1.0.post13+f9c3afeaf
    conda-build version : 3.23.3
         python version : 3.9.16.final.0
       virtual packages : __archspec=1=x86_64
                          __glibc=2.31=0
                          __linux=6.0.7=0
                          __unix=0=0
       base environment : /opt/conda  (read only)
      conda av data dir : /opt/conda/etc/conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
          package cache : /opt/conda/pkgs
                          /home/test_user/.conda/pkgs
       envs directories : /home/test_user/.conda/envs
                          /opt/conda/envs
               platform : linux-64
             user-agent : conda/23.1.0.post13+f9c3afeaf requests/2.28.1 CPython/3.9.16 Linux/6.0.7 debian/11 glibc/2.31 solver/libmamba conda-libmamba-solver/22.8.1 libmambapy/1.0.0
                UID:GID : 1001:1001
             netrc file : None
           offline mode : False
````

Then ran `conda create -n test numpy` and had the following output

````shell
(base) test_user@7ed5bc4c9c4b:/opt/conda/pkgs/cache$ conda create -n test numpy
conda-forge/linux-64                                        Using cache
conda-forge/noarch                                          Using cache
Collect all metadata (repodata.json): done
Solving environment: done
```

Just to check on things I then ran `conda create -c defaults -n test numpy` and got the following output

`````shell
(base) test_user@7ed5bc4c9c4b:/opt/conda/pkgs/cache$ conda create -c defaults -n test numpy
conda-forge/linux-64                                        Using cache
conda-forge/noarch                                          Using cache
pkgs/main/linux-64                                            No change
pkgs/main/noarch                                              No change
pkgs/r/linux-64                                               No change
pkgs/r/noarch                                                 No change
...
````` 

So this works as expected with the docker image from what I can tell.

**Comment by costrouc** [comment]
Now running from a blank starting docker image

````shell
docker run -it condaforge/mambaforge bash
$ conda install conda-libmamba-solver -y
````

````shell
printf "channels: ['conda-forge']\nsolver: libmamba\n" > ~/.condarc
````

Then checking `conda info`

```shell

     active environment : base
    active env location : /opt/conda
            shell level : 1
       user config file : /root/.condarc
 populated config files : /opt/conda/.condarc
                          /root/.condarc
          conda version : 22.11.1
    conda-build version : not installed
         python version : 3.10.8.final.0
       virtual packages : __archspec=1=x86_64
                          __glibc=2.31=0
                          __linux=6.0.7=0
                          __unix=0=0
       base environment : /opt/conda  (writable)
      conda av data dir : /opt/conda/etc/conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
          package cache : /opt/conda/pkgs
                          /root/.conda/pkgs
       envs directories : /opt/conda/envs
                          /root/.conda/envs
               platform : linux-64
             user-agent : conda/22.11.1 requests/2.28.1 CPython/3.10.8 Linux/6.0.7 ubuntu/20.04.5 glibc/2.31 solver/libmamba conda-libmamba-solver/22.8.1 libmambapy/1.1.0                UID:GID : 0:0
             netrc file : None
           offline mode : False
```

Finally I attempted the same solve as before

`````shell
(base) root@1114e1f2bea2:/# conda create -n test numpy
conda-forge/noarch                                  11.1MB @   3.8MB/s  3.1s
conda-forge/linux-64                                29.5MB @   4.3MB/s  7.5s
````

This was using `conda-libmamba-solver/23.1.0` . I also attempted `22.11.0`  with the same results... sorry @andreostrovsky that I haven't been able to reproduce this.

Are you still running into this issue?

**Comment by andreostrovsky** [comment]
@costrouc 
> Are you still running into this issue?

Yes nothing has changed. Same package versions as in my first post. 
Doing any conda action that involves a solve
when `.condarc` contains `solver: libmamba`:

```shell
> conda remove matplotlib-venn
pkgs/r/win-64                                      742.8kB @ 560.1kB/s  1.5s
pkgs/msys2/noarch                                  111.0 B @  72.0kB/s  0.3s
pkgs/main/noarch                                   818.9kB @ 437.0kB/s  2.0s
pkgs/msys2/win-64                                   39.8kB @  19.4kB/s  0.2s
pkgs/r/noarch                                        1.3MB @ 441.8kB/s  1.5s
pkgs/main/win-64                                     4.6MB @ 603.6kB/s  8.1s
remote-conda-forge-public/win-64                    79.5MB @   1.0MB/s 1m:18.9s
remote-conda-forge-public/noarch                   156.1MB @   1.3MB/s 1m:59.9s
Collect all metadata (repodata.json): done
Solving environment: done
```

And without `solver: libmamba`, conda doesn't print out the repodata sources as it downloads them, but I deleted the contents of `prefix/pkgs/cache` and confirmed that after running only 2 sources were downloaded.

When using mamba instead:
```shell
> mamba install matplotlib-venn

<mamba logo>

Looking for: ['matplotlib-venn']

remote-conda-forge-public/win-64                    79.5MB @   1.3MB/s 1m:3.0s
remote-conda-forge-public/noarch                  156.1MB @   1.3MB/s 2m:2.3s
```

**Comment by costrouc** [comment]
So today I learned about the value of the verbosity option when running `conda create ...` . I am still not able to reproduce this. I tried this on windows/linux/and osx. See https://github.com/costrouc/conda-libmamba-solver-reproducibility/actions/runs/4147530753/jobs/7174516293#step:6:175.

When running with the `-vv` option I can get detailed info on what libmamba/conda is doing.

Here I see the lines

````shell
...
info     libmamba Transfer done for 'conda-forge/noarch'
....
info     libmamba Transfer done for 'conda-forge/win-64'
...

I got this from searching for the term "libmamba Transfer done". I've search for a few other terms like "Cache path" in the logs and there are only two paths being touched. `defaults` seem to be untouched.

@andreostrovsky could you run with the `-vv` flag when running the install. And check for lines `libmamba Searching index cache file for repo`. 
````

**Comment by jaimergp** [comment]
xref https://github.com/conda/conda/issues/12136

**Comment by ColemanTom** [comment]
Adding `#!final` did not resolve this for me. It removed the addition of `https://repo.anaconda.com/pkgs/main`, but instead added my local artifactory instance (without the username and identity token), and thus fails due to failed authentication.

My environment is an area without access to the external world. To mimic the failures you should block anything except internal mirrors. All my channels are `https://username:token@artifactory....` type syntax.

It appears that the `current_channels` provided add extra things that are different to the `context.channels`.  Looking a bit more, the section:

```python
      # See https://github.com/conda/conda/issues/11790
        channels_from_installed = []
        for record in installed_records:
            if record.channel.auth or record.channel.token:
                # skip if the channel has authentication info, because
                # it might cause issues with expired tokens and what not
                continue
            if record.channel.name in ("@", "<develop>", "pypi"):
                # These "channels" are not really channels, more like
                # metadata placeholders
                continue
            if record.channel.subdir_url not in channels_from_installed:
                channels_from_installed.append(record.channel.subdir_url)
```

is getting channels defined in the `conda-meta` files. The problem with that is those channels have stripped out the credentials (but they have not been stripped out for the `url` section down the bottom which I am not liking as it could expose personal credentials to the world if your HOME directory is world readable). 

So, if I remove that `channels_from_installed` section, things work in locked down environments where credentials are requried but not stored in the conda-meta file. Perhaps a configuration option to not get channels from installed packages would resolve this bug?

**Comment by jaimergp** [comment]
That's super insightful and would explain why we couldn't reproduce with bare 'conda create' (there was no environment to pull channel packages from).

Right now we don't have a plugin settings mechanism but we might be able to add an environment variable to control for this edge case. I think we can also use `migrated_*` settings ([search here](https://docs.conda.io/projects/conda/en/latest/configuration.html)) to offer you better control on how these channels are being used (they are technically not new channels, but mirrors, so we can map between the original source and the one being used to access it).

Thank you so much for looking into it, I am now sure we can fix this! 💪

**Comment by jaimergp** [comment]
Thinking about it, this might also be a bug where we are not overriding the generated `conda-meta` info. Could you confirm whether the channels listed in `conda-meta` are correctly set to the authenticated ones _if_ you use `solver=classic`? I don't think they are but 🤷

**Comment by ColemanTom** [comment]
classic - strips out authentication.

I can provide a fix for this, but then another error appears later saying the solve will fail, but it doesn't. I'm guessing it must be in the C level code? I haven't looked there.

```
Collect all metadata (repodata.json): done
Solving environment: | error    libmamba Selected channel specific (or force-reinstall) job, but package is not available from channel. Solve job will fail.
error    libmamba Selected channel specific (or force-reinstall) job, but package is not available from channel. Solve job will fail.
error    libmamba Selected channel specific (or force-reinstall) job, but package is not available from channel. Solve job will fail.
done

# All requested packages already installed.
```

The block I pasted above, I added an extra if statement:

```
            if self._is_record_in_authless_channels(record):
                # Check if this record already exists in the channels, ensuring
                # authentication strings are removed from the search.
                continue
```

Which is calling this function:

```
    def _is_record_in_authless_channels(self, record: PackageRecord) -> bool:
        """
        Check if the record exists in any existing channel specification. It is
        possible that the channel already exists with authentication provided and
        should not be added in again.

        If it is added in, without authentication, it can lead to failures when downloading
        the updated repodata.json information due to authentication failures.

        See: https://github.com/conda/conda-libmamba-solver/issues/108
        """
        for channel in self._channels:
            if str(record.channel).startswith(str(channel)):
                return True
        return False
```

This prevents the extra channels being added. But as mentioned, there must be something else later that checks the channel again when solving. I'm not going to go any further with this one - but I think this should give a good indication of an approach that works, even if it isn't the best option.

**Comment by jaimergp** [comment]
Yea those are coming from the libmamba library. I [posted an issue upstream](https://github.com/mamba-org/mamba/issues/1924) a while ago because I also find them a bit too alarming... We "fixed" that error by preloading the foreign channels but in gets in the way in this use case. Your fix is essentially undoing the last if clause in our for loop:

```python
if record.channel.subdir_url not in channels_from_installed:
    channels_from_installed.append(record.channel.subdir_url)
```

I think we can have some logic to compare whether the packages are being downloaded from the channel they claim to belong to, and keep a map as needed. I'll open a PR next week!

**Comment by ColemanTom** [comment]
One thing I forgot to mention. For the libmamba error messages, I did start to look at the data passed to the solver, but concluded it would take me too long to understand how it worked and the impacts of modifying anything there, so I abandoned looking.

Thanks for looking into how to fix this properly.

**Comment by jaimergp** [comment]
I am debugging this now. I am first checking whether `conda` stores the right channel in `conda-meta` when downloading from a mirror and, to my surprise, it does. I think the mapping is done [in this function](https://github.com/conda/conda/blob/a743030920f8ddd5f1ab3b6f69f5217d27190fa4/conda/gateways/disk/read.py#L104-L120): `record` (the metadata object returned by the solver) is mapped to `package_cache_record` (the downloaded and extracted artifact in the cache). You can see how the channel is set to the one provided by `record`, so it should be the mirror URL, not the original source.

This does not align with what we are observing here, but I haven't checked what happens with authentication.

To be extra sure, can you check what happens with the following command?

```shell
$ conda create -n test-channels --override-channels -c "https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge" --solver libmamba dav1d
$ conda activate test-channels
$ cat "$CONDA_PREFIX/conda-meta/dav1d-*.json"
```

Ideally, can you repeat it with your artifactory mirror and see if the same thing happens? 
- The conda-meta JSON file should list the mirrored URL, not the original conda-forge source.
- The `about.json` file in `$CONDA/pkgs/dav1d-*` does report the original conda-forge source.

**Comment by jaimergp** [comment]
@ColemanTom, I re-read your message and I get it now. Your issue can be fixed with better de-duplication in `LibMambaIndexHelper._load_channels()` (checking if the de-auth'd URLs are in `seen`, instead of the auth'd ones). A PR will come soon.

So it looks like a combination of `#!final` and that fix would get us closer to a solution. @andreostrovsky, can you check if the scenario described by @ColemanTom reproduces for you too? Thanks! 🙏

**Comment by swails** [comment]
FWIW, this is biting me, too.  We've set up `channel_alias` to prioritize our Artifactory repositories, and add `conda-forge` explicitly at the end.  Something like the following in our `.condarc`:

```
channel_alias: https://username:password@domain.jfrog.io/artifactory/api/conda
channels:
  - conda-domain-private
  - https://conda.anaconda.org/conda-forge
show_channel_urls: true
```

When trying to `mamba install conda-libmamba-solver`, I get something like:

```
    RuntimeError: Multi-download failed. Reason: Transfer finalized, status: 500 [https://username:token@domain.jfrog.io/artifactory/api/conda/conda-forge/noarch/repodata.json] 117 bytes

`$ /opt/conda/bin/mamba install conda-libmamba-solver`

  environment variables:
                 CIO_TEST=<not set>
        CONDA_DEFAULT_ENV=base
                CONDA_DIR=/opt/conda
                CONDA_EXE=/opt/conda/bin/conda
             CONDA_PREFIX=/opt/conda
    CONDA_PROMPT_MODIFIER=(base)
         CONDA_PYTHON_EXE=/opt/conda/bin/python
               CONDA_ROOT=/opt/conda
              CONDA_SHLVL=1
           CURL_CA_BUNDLE=<not set>
               LD_PRELOAD=<not set>
                     PATH=/opt/conda/bin:/opt/conda/condabin:/opt/conda/bin:/usr/local/sbin:/usr
                          /local/bin:/usr/sbin:/usr/bin:/sbin:/bin
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>

     active environment : base
    active env location : /opt/conda
            shell level : 1
       user config file : /root/.condarc
 populated config files : /opt/conda/.condarc
                          /root/.condarc
          conda version : 22.11.1
    conda-build version : not installed
         python version : 3.10.9.final.0
       virtual packages : __archspec=1=x86_64
                          __glibc=2.31=0
                          __linux=5.10.104=0
                          __unix=0=0
       base environment : /opt/conda  (writable)
      conda av data dir : /opt/conda/etc/conda
  conda av metadata url : None
           channel URLs : https://username:token@domain.jfrog.io/artifactory/api/conda/conda-domain-private/linux-64
                          https://username:token@domain.jfrog.io/artifactory/api/conda/conda-domain-private/noarch
                          https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://username:token@domain.jfrog.io/artifactory/api/conda/conda-forge/linux-64
                          https://username:token@domain.jfrog.io/artifactory/api/conda/conda-forge/noarch
          package cache : /opt/conda/pkgs
                          /root/.conda/pkgs
       envs directories : /opt/conda/envs
                          /root/.conda/envs
               platform : linux-64
             user-agent : conda/22.11.1 requests/2.28.2 CPython/3.10.9 Linux/5.10.104-linuxkit ubuntu/20.04.5 glibc/2.31
                UID:GID : 0:0
             netrc file : None
           offline mode : False


An unexpected error has occurred. Conda has prepared the above report.
```

Note that with mamba 0.4.2, this works fine.

My best guess for what's happening here is that mamba seems to require conda-forge availability for some reason, and if none of the channels matches `conda-forge`, it gets added internally.

The workaround for me seems to be to create an (empty) `conda-forge` conda repository in Artifactory so that the channel alias added by mamba resolves to *something*, rather than throwing up a 500 from Artifactory.  I'm trying that now and will report back if it "works".

**Comment by swails** [comment]
UPDATE: I know this is an unsatisfying workaround, and will not help people that do not have the permission to do this, but if you can add a `conda-forge` channel to the `channel_alias` site (even if it's an empty channel with no packages), I can confirm that mamba stops crashing and this workaround works.

In Artifactory this is easy.  Not sure about other mirrors.

**Comment by jezdez** [comment]
Thanks @swails, I've lowered the severity a notch given that we have a workaround, even if great.
