### ISSUE TITLE
Anaconda hotfix doesn't know about new release

### ISSUE THREAD

**Issue by dholth** [conda/conda-libmamba-solver#132]
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### What happened?

I know this is the wrong repository, but https://github.com/AnacondaRecipes/repodata-hotfixes/blob/master/main.py#L1113 needs to be updated to be aware of the newest conda-libmamba-solver.

**Comment by jaimergp** [comment]
Good catch! Sent https://github.com/AnacondaRecipes/repodata-hotfixes/pull/183
