### ISSUE TITLE
LibMambaIndexHelper failure in airgapped miniconda install

### ISSUE THREAD

**Issue by tholam** [conda/conda-libmamba-solver#146]
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### What happened?

When using the libmamba solver in an airgapped miniconda environment that still
contains packages from repo.anaconda.com packaged with the installer, LibMambaIndexHelper
will try to add repo.anaconda.com to the list of channels to load even if you've
configured conda to only use some internally hosted package repository.

This seems to be because of this change
https://github.com/conda/conda-libmamba-solver/pull/52

If unable to download the repodata from repo.anaconda.com an exception is raised even though
the channel was not requested from the end user point of view.

**Comment by costrouc** [comment]
@tholam thank for the issue! Might this be related to https://github.com/conda/conda-libmamba-solver/issues/108? In this issue similarly the anaconda main channel is being loaded when not specified by the user.

**Comment by tholam** [comment]
@costrouc it does look very similar although I'm not sure if it's the exact same problem as OP had mentioned

> There are no packages installed in the environment from any of these channels.

In my case I can confirm that if I'm creating a fresh environment it does not fetch repo.anaconda.com

```
import tempfile
from conda.api import Solver
solver = Solver(tempfile.mkdtemp(), channels=channels, subdirs=context.subdirs, specs_to_add=specs)
final_state = solver.solve_final_state()
```

**Comment by tholam** [comment]
This comment https://github.com/conda/conda-libmamba-solver/issues/108#issuecomment-1451322796 does look like the same thing I'm seeing

**Comment by jaimergp** [comment]
Excellent. I am working on this now. Please watch #108 for updates. I'll close this one as dup! 🙏
