### ISSUE TITLE
Change in conda solver interface due to boltons moving away from being Vendored

### ISSUE THREAD

**Issue by costrouc** [conda/conda-libmamba-solver#153]
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### What happened?

Due to PR https://github.com/conda/conda/pull/12453 Boltons is no longer vendored by default. I see two approach for importing IndexedSet and I would prefer the later so that we directly depend on conda to specify the IndexedSet. Avoiding the potentital situation where an older conda is used and boltons is installed.

```python
try:
    from boltons.setutils import IndexedSet
except ImportError:
    from conda._vendor.boltons.setutils import IndexedSet
```

or

```
from conda.core.solve import IndexedSet
```

### Conda Info

```shell
N/A
```

### Conda Config

```shell
N/A
```

### Conda list

```shell
N/A
```

**Comment by jezdez** [comment]
FWIW boltons is still vendored but just marked for deprecation, meaning that it'll follow the [CEP 9](https://github.com/conda-incubator/ceps/blob/main/cep-9.md).
