### ISSUE TITLE
Conflicts with a fresh install of Anaconda 2023.03-0

### ISSUE THREAD

**Issue by complyue** [conda/conda-libmamba-solver#169]
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### What happened?

% conda install -n base conda-libmamba-solver
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: - 
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.

UnsatisfiableError: The following specifications were found
to be incompatible with the existing python installation in your environment:

Specifications:

  - backports -> python[version='>=2.7,<2.8.0a0|>=3.5,<3.6.0a0|>=3.7,<3.8.0a0|>=3.6,<3.7.0a0']
  - backports.functools_lru_cache -> python[version='>=2.7,<2.8.0a0']
  - brotlipy -> python[version='>=2.7,<2.8.0a0|>=3.5,<3.6.0a0']
  - conda-content-trust -> python[version='>=2.7,<2.8.0a0|>=3.6,<3.7.0a0|>=3.5,<3.6.0a0']
  - conda-package-streaming -> python[version='>=3.6,<3.7.0a0']
  - conda-verify -> python[version='>=2.7,<2.8.0a0|>=3.6,<3.7.0a0|>=3.7,<3.8.0a0|>=3.5,<3.6.0a0']
  - defusedxml -> python[version='>=2.7,<2.8.0a0|>=3.5,<3.6.0a0|>=3.6,<3.7.0a0|>=3.7,<3.8.0a0']
  - glob2 -> python[version='>=2.7,<2.8.0a0|>=3.7,<3.8.0a0|>=3.6,<3.7.0a0|>=3.5,<3.6.0a0']
  - pathlib -> python[version='>=2.7,<2.8.0a0|>=3.8,<3.9.0a0|>=3.6,<3.7.0a0|>=3.7,<3.8.0a0']
  - pyrsistent -> python[version='>=3.5,<3.6.0a0']
  - python-dateutil -> python[version='>=2.7,<2.8.0a0|>=3.6,<3.7.0a0|>=3.7,<3.8.0a0|>=3.5,<3.6.0a0']
  - python-dateutil -> python[version='>=3.8,<3.9.0a0|>=3.9,<3.10.0a0']
  - python-libarchive-c -> python[version='>=2.7,<2.8.0a0|>=3.6,<3.7.0a0|>=3.9,<3.10.0a0|>=3.7,<3.8.0a0|>=3.8,<3.9.0a0|>=3.5,<3.6.0a0']
  - ruamel.yaml -> python[version='>=2.7,<2.8.0a0|>=3.5,<3.6.0a0']
  - six -> python[version='>=2.7,<2.8.0a0|>=3.6,<3.7.0a0|>=3.8,<3.9.0a0|>=3.9,<3.10.0a0|>=3.7,<3.8.0a0|>=3.5,<3.6.0a0']
  - soupsieve -> python[version='>=3.5,<3.6.0a0']
  - zstandard -> python[version='>=3.5,<3.6.0a0']

Your python: python=3.10

If python is on the left-most side of the chain, that's the version you've asked for.
When python appears to the right, that indicates that the thing on the left is somehow
not available for the python version you are constrained to. Note that conda will not
change your python version to a different minor version unless you explicitly specify
that.

The following specifications were found to be incompatible with a past
explicit spec that is not an explicit spec in this operation (conda-package-handling):

  - conda-libmamba-solver -> conda[version='>=22.11.0,<23.1.0a|>=22.11.0,<23.2.0a|>=4.13,<22.11.0a|>=4.12']
  - conda-libmamba-solver -> conda[version='>=22.11.0,<23.2.0a'] -> conda-package-handling[version='>=1.3.0']
  - conda-libmamba-solver -> conda[version='>=22.11.0,<23.2.0a'] -> setuptools[version='>=31.0.1']

The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versions

Package openssl conflicts for:
urllib3 -> cryptography[version='>=1.3.4'] -> openssl[version='1.0.*|>=1.0.2o,<1.0.3a|>=1.0.2p,<1.0.3a|>=1.1.1a,<1.1.2a|>=1.1.1b,<1.1.2a|>=1.1.1c,<1.1.2a|>=1.1.1d,<1.1.2a|>=1.1.1g,<1.1.2a|>=1.1.1h,<1.1.2a|>=1.1.1i,<1.1.2a|>=1.1.1j,<1.1.2a|>=1.1.1k,<1.1.2a|>=1.1.1l,<1.1.2a|>=1.0.2n,<1.0.3a|>=1.0.2m,<1.0.3a|>=1.1.1t,<1.1.2a|>=1.1.1s,<1.1.2a|>=1.1.1q,<1.1.2a|>=1.1.1n,<1.1.2a|>=1.1.1m,<1.1.2a|>=1.1.1e,<1.1.2a|>=1.1.1o,<1.1.2a|>=1.0.2l,<1.0.3a']
pillow -> python[version='>=3.11,<3.12.0a0'] -> openssl[version='1.0.*|>=1.0.2m,<1.0.3a|>=1.0.2n,<1.0.3a|>=1.0.2o,<1.0.3a|>=1.1.1a,<1.1.2a|>=1.1.1b,<1.1.2a|>=1.1.1c,<1.1.2a|>=1.1.1d,<1.1.2a|>=1.1.1e,<1.1.2a|>=1.1.1g,<1.1.2a|>=1.1.1j,<1.1.2a|>=1.1.1k,<1.1.2a|>=1.1.1l,<1.1.2a|>=1.1.1n,<1.1.2a|>=1.1.1q,<1.1.2a|>=1.1.1s,<1.1.2a|>=1.1.1t,<1.1.2a|>=1.1.1m,<1.1.2a|>=1.1.1o,<1.1.2a|>=1.1.1i,<1.1.2a|>=1.1.1h,<1.1.2a|>=1.0.2l,<1.0.3a|>=1.0.2p,<1.0.3a']
python.app -> python[version='>=3.11,<3.12.0a0'] -> openssl[version='1.0.*|>=1.0.2m,<1.0.3a|>=1.0.2n,<1.0.3a|>=1.0.2o,<1.0.3a|>=1.1.1a,<1.1.2a|>=1.1.1b,<1.1.2a|>=1.1.1c,<1.1.2a|>=1.1.1d,<1.1.2a|>=1.1.1e,<1.1.2a|>=1.1.1g,<1.1.2a|>=1.1.1j,<1.1.2a|>=1.1.1k,<1.1.2a|>=1.1.1l,<1.1.2a|>=1.1.1m,<1.1.2a|>=1.1.1n,<1.1.2a|>=1.1.1q,<1.1.2a|>=1.1.1s,<1.1.2a|>=1.1.1t,<1.1.2a|>=1.1.1o,<1.1.2a|>=1.1.1i,<1.1.2a|>=1.1.1h,<1.1.2a|>=1.0.2l,<1.0.3a|>=1.0.2p,<1.0.3a']
conda-token -> python -> openssl[version='1.0.*|>=1.0.2m,<1.0.3a|>=1.0.2n,<1.0.3a|>=1.0.2o,<1.0.3a|>=1.1.1a,<1.1.2a|>=1.1.1b,<1.1.2a|>=1.1.1c,<1.1.2a|>=1.1.1d,<1.1.2a|>=1.1.1e,<1.1.2a|>=1.1.1g,<1.1.2a|>=1.1.1h,<1.1.2a|>=1.1.1i,<1.1.2a|>=1.1.1j,<1.1.2a|>=1.1.1k,<1.1.2a|>=1.1.1l,<1.1.2a|>=1.1.1m,<1.1.2a|>=1.1.1n,<1.1.2a|>=1.1.1q,<1.1.2a|>=1.1.1s,<1.1.2a|>=1.1.1t,<1.1.2a|>=1.1.1o,<1.1.2a|>=1.0.2l,<1.0.3a|>=1.0.2p,<1.0.3a']
cryptography -> openssl[version='1.0.*|>=1.0.2o,<1.0.3a|>=1.0.2p,<1.0.3a|>=1.1.1a,<1.1.2a|>=1.1.1b,<1.1.2a|>=1.1.1c,<1.1.2a|>=1.1.1d,<1.1.2a|>=1.1.1g,<1.1.2a|>=1.1.1h,<1.1.2a|>=1.1.1i,<1.1.2a|>=1.1.1j,<1.1.2a|>=1.1.1k,<1.1.2a|>=1.1.1l,<1.1.2a|>=1.0.2n,<1.0.3a|>=1.0.2m,<1.0.3a']
libmambapy -> openssl[version='>=1.1.1o,<1.1.2a|>=1.1.1s,<1.1.2a|>=1.1.1t,<1.1.2a']
conda-package-streaming -> python[version='>=3.11,<3.12.0a0'] -> openssl[version='>=1.0.2o,<1.0.3a|>=1.1.1a,<1.1.2a|>=1.1.1b,<1.1.2a|>=1.1.1c,<1.1.2a|>=1.1.1d,<1.1.2a|>=1.1.1e,<1.1.2a|>=1.1.1g,<1.1.2a|>=1.1.1j,<1.1.2a|>=1.1.1k,<1.1.2a|>=1.1.1l,<1.1.2a|>=1.1.1m,<1.1.2a|>=1.1.1n,<1.1.2a|>=1.1.1q,<1.1.2a|>=1.1.1s,<1.1.2a|>=1.1.1t,<1.1.2a|>=1.1.1o,<1.1.2a|>=1.1.1i,<1.1.2a|>=1.1.1h,<1.1.2a']
ujson -> python[version='>=3.11,<3.12.0a0'] -> openssl[version='1.0.*|>=1.0.2m,<1.0.3a|>=1.0.2n,<1.0.3a|>=1.0.2o,<1.0.3a|>=1.1.1a,<1.1.2a|>=1.1.1b,<1.1.2a|>=1.1.1c,<1.1.2a|>=1.1.1d,<1.1.2a|>=1.1.1e,<1.1.2a|>=1.1.1g,<1.1.2a|>=1.1.1j,<1.1.2a|>=1.1.1k,<1.1.2a|>=1.1.1n,<1.1.2a|>=1.1.1q,<1.1.2a|>=1.1.1s,<1.1.2a|>=1.1.1t,<1.1.2a|>=1.1.1m,<1.1.2a|>=1.1.1l,<1.1.2a|>=1.1.1o,<1.1.2a|>=1.1.1i,<1.1.2a|>=1.1.1h,<1.1.2a|>=1.0.2l,<1.0.3a|>=1.0.2p,<1.0.3a']
cryptography -> python[version='>=3.11,<3.12.0a0'] -> openssl[version='>=1.0.2l,<1.0.3a|>=1.1.1e,<1.1.2a|>=1.1.1m,<1.1.2a|>=1.1.1n,<1.1.2a|>=1.1.1q,<1.1.2a|>=1.1.1s,<1.1.2a|>=1.1.1t,<1.1.2a|>=1.1.1o,<1.1.2a']
packaging -> python[version='>=3.8,<3.9.0a0'] -> openssl[version='1.0.*|>=1.0.2m,<1.0.3a|>=1.0.2n,<1.0.3a|>=1.0.2o,<1.0.3a|>=1.1.1a,<1.1.2a|>=1.1.1b,<1.1.2a|>=1.1.1c,<1.1.2a|>=1.1.1d,<1.1.2a|>=1.1.1e,<1.1.2a|>=1.1.1g,<1.1.2a|>=1.1.1j,<1.1.2a|>=1.1.1k,<1.1.2a|>=1.1.1l,<1.1.2a|>=1.1.1n,<1.1.2a|>=1.1.1q,<1.1.2a|>=1.1.1s,<1.1.2a|>=1.1.1t,<1.1.2a|>=1.1.1m,<1.1.2a|>=1.1.1o,<1.1.2a|>=1.1.1i,<1.1.2a|>=1.1.1h,<1.1.2a|>=1.0.2l,<1.0.3a|>=1.0.2p,<1.0.3a']
cffi -> python[version='>=3.11,<3.12.0a0'] -> openssl[version='1.0.*|>=1.0.2m,<1.0.3a|>=1.0.2n,<1.0.3a|>=1.0.2o,<1.0.3a|>=1.1.1a,<1.1.2a|>=1.1.1b,<1.1.2a|>=1.1.1c,<1.1.2a|>=1.1.1d,<1.1.2a|>=1.1.1e,<1.1.2a|>=1.1.1g,<1.1.2a|>=1.1.1j,<1.1.2a|>=1.1.1k,<1.1.2a|>=1.1.1l,<1.1.2a|>=1.1.1n,<1.1.2a|>=1.1.1q,<1.1.2a|>=1.1.1s,<1.1.2a|>=1.1.1t,<1.1.2a|>=1.1.1o,<1.1.2a|>=1.1.1i,<1.1.2a|>=1.1.1h,<1.1.2a|>=1.1.1m,<1.1.2a|>=1.0.2l,<1.0.3a|>=1.0.2p,<1.0.3a']
mamba -> openssl[version='>=1.1.1o,<1.1.2a']
...

### Conda Info

```shell
active environment : None
            shell level : 0
       user config file : /Users/cyue/.condarc
 populated config files : /Users/cyue/.condarc
          conda version : 23.3.0
    conda-build version : 3.23.3
         python version : 3.10.9.final.0
       virtual packages : __archspec=1=x86_64
                          __osx=10.16=0
                          __unix=0=0
       base environment : /fw/m3cyue/Darwin/apps/anaconda3  (writable)
      conda av data dir : /fw/m3cyue/Darwin/apps/anaconda3/etc/conda
  conda av metadata url : None
           channel URLs : https://repo.anaconda.com/pkgs/main/osx-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/osx-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /fw/m3cyue/Darwin/apps/anaconda3/pkgs
                          /Users/cyue/.conda/pkgs
       envs directories : /fw/m3cyue/Darwin/apps/anaconda3/envs
                          /Users/cyue/.conda/envs
               platform : osx-64
             user-agent : conda/23.3.0 requests/2.28.1 CPython/3.10.9 Darwin/21.6.0 OSX/10.16
                UID:GID : 501:20
             netrc file : None
           offline mode : False
```

### Conda Config

```shell
==> /Users/cyue/.condarc <==
auto_activate_base: False
channels:
  - defaults
show_channel_urls: True
```

### Conda list

```shell
# packages in environment at /fw/m3cyue/Darwin/apps/anaconda3:
#
# Name                    Version                   Build  Channel
anaconda-client           1.11.1          py310hecd8cb5_0    defaults
anaconda-navigator        2.4.0           py310hecd8cb5_0    defaults
anaconda-project          0.11.1          py310hecd8cb5_0    defaults
attrs                     22.1.0          py310hecd8cb5_0    defaults
backports                 1.1                pyhd3eb1b0_0    defaults
backports.functools_lru_cache 1.6.4              pyhd3eb1b0_0    defaults
backports.tempfile        1.0                pyhd3eb1b0_1    defaults
backports.weakref         1.0.post1                  py_1    defaults
beautifulsoup4            4.11.1          py310hecd8cb5_0    defaults
black                     22.6.0          py310hecd8cb5_0    defaults
boltons                   23.0.0          py310hecd8cb5_0    defaults
brotlipy                  0.7.0           py310hca72f7f_1002    defaults
bzip2                     1.0.8                h1de35cc_0    defaults
c-ares                    1.19.0               h6c40b1e_0    defaults
ca-certificates           2022.12.7            h033912b_0    conda-forge
cctools                   949.0.1             h9abeeb2_25    defaults
cctools_osx-64            949.0.1             hc7db93f_25    defaults
certifi                   2022.12.7          pyhd8ed1ab_0    conda-forge
cffi                      1.15.1          py310h6c40b1e_3    defaults
chardet                   4.0.0           py310hecd8cb5_1003    defaults
charset-normalizer        2.0.4              pyhd3eb1b0_0    defaults
click                     8.0.4           py310hecd8cb5_0    defaults
clyent                    1.2.2           py310hecd8cb5_1    defaults
conda                     23.3.0          py310h2ec42d9_0    conda-forge
conda-build               3.23.3          py310hecd8cb5_0    defaults
conda-content-trust       0.1.3           py310hecd8cb5_0    defaults
conda-pack                0.6.0              pyhd3eb1b0_0    defaults
conda-package-handling    2.0.2           py310hecd8cb5_0    defaults
conda-package-streaming   0.7.0           py310hecd8cb5_0    defaults
conda-repo-cli            1.0.41          py310hecd8cb5_0    defaults
conda-token               0.4.0              pyhd3eb1b0_0    defaults
conda-verify              3.4.2                      py_1    defaults
cryptography              39.0.1          py310hf6deb26_0    defaults
defusedxml                0.7.1              pyhd3eb1b0_0    defaults
filelock                  3.9.0           py310hecd8cb5_0    defaults
freetype                  2.12.1               hd8bbffd_0    defaults
future                    0.18.3          py310hecd8cb5_0    defaults
gettext                   0.21.0               h7535e17_0    defaults
giflib                    5.2.1                h6c40b1e_3    defaults
glib                      2.69.1               hfff2838_2    defaults
glob2                     0.7                pyhd3eb1b0_0    defaults
gst-plugins-base          1.14.1               hcec6c5f_1    defaults
gstreamer                 1.14.1               h6c40b1e_1    defaults
icu                       58.2                 h0a44026_3    defaults
idna                      3.4             py310hecd8cb5_0    defaults
jinja2                    3.1.2           py310hecd8cb5_0    defaults
jpeg                      9e                   h6c40b1e_1    defaults
jsonschema                4.17.3          py310hecd8cb5_0    defaults
jupyter_core              5.3.0           py310hecd8cb5_0    defaults
krb5                      1.19.4               hdba6334_0    defaults
lcms2                     2.12                 hf1fd2bf_0    defaults
ld64                      530                 h20443b4_25    defaults
ld64_osx-64               530                 h70f3046_25    defaults
ldid                      2.1.2                h2d21305_2    defaults
lerc                      3.0                  he9d5cce_0    defaults
libarchive                3.5.2                ha0e9c3a_0    defaults
libclang                  12.0.0          default_hbc2896b_2    defaults
libcurl                   7.88.1               ha585b31_0    defaults
libcxx                    14.0.6               h9765a3e_0    defaults
libdeflate                1.17                 hb664fd8_0    defaults
libedit                   3.1.20221030         h6c40b1e_0    defaults
libev                     4.33                 h9ed2024_1    defaults
libffi                    3.4.2                hecd8cb5_6    defaults
libiconv                  1.16                 hca72f7f_2    defaults
liblief                   0.12.3               hcec6c5f_0    defaults
libllvm12                 12.0.0               h9b2ccf5_3    defaults
libllvm14                 14.0.6               h91fad77_1    defaults
libmamba                  0.24.0               h2d3d89a_1    conda-forge
libmambapy                0.24.0          py310hdd39e55_1    conda-forge
libnghttp2                1.46.0               ha29bfda_0    defaults
libpng                    1.6.39               h6c40b1e_0    defaults
libpq                     12.9                 h1c9f633_3    defaults
libsolv                   0.7.22               h8346a28_0    defaults
libssh2                   1.10.0               h0a4fc7d_0    defaults
libtiff                   4.5.0                hcec6c5f_2    defaults
libwebp                   1.2.4                hf6ce154_1    defaults
libwebp-base              1.2.4                h6c40b1e_1    defaults
libxml2                   2.9.14               hbf8cd5e_0    defaults
libxslt                   1.1.35               h5b33f42_0    defaults
llvm-openmp               14.0.6               h0dcd299_0    defaults
lz4-c                     1.9.4                hcec6c5f_0    defaults
mamba                     0.24.0          py310h795411f_1    conda-forge
markupsafe                2.1.1           py310hca72f7f_0    defaults
mypy_extensions           0.4.3           py310hecd8cb5_1    defaults
navigator-updater         0.3.0           py310hecd8cb5_0    defaults
nbformat                  5.7.0           py310hecd8cb5_0    defaults
ncurses                   6.4                  hcec6c5f_0    defaults
nspr                      4.33                 he9d5cce_0    defaults
nss                       3.74                 h47edf6a_0    defaults
openssl                   1.1.1t               hfd90126_0    conda-forge
packaging                 23.0            py310hecd8cb5_0    defaults
patch                     2.7.6             h1de35cc_1001    defaults
pathlib                   1.0.1              pyhd3eb1b0_1    defaults
pathspec                  0.10.3          py310hecd8cb5_0    defaults
pcre                      8.45                 h23ab428_0    defaults
pcre2                     10.37                he7042d7_1    defaults
pillow                    9.4.0           py310hcec6c5f_0    defaults
pip                       22.3.1          py310hecd8cb5_0    defaults
pkginfo                   1.9.6           py310hecd8cb5_0    defaults
platformdirs              2.5.2           py310hecd8cb5_0    defaults
pluggy                    1.0.0           py310hecd8cb5_1    defaults
ply                       3.11            py310hecd8cb5_0    defaults
psutil                    5.9.0           py310hca72f7f_0    defaults
py-lief                   0.12.3          py310hcec6c5f_0    defaults
pybind11-abi              4                    hd3eb1b0_0    defaults
pycosat                   0.6.4           py310hca72f7f_0    defaults
pycparser                 2.21               pyhd3eb1b0_0    defaults
pyjwt                     2.4.0           py310hecd8cb5_0    defaults
pyopenssl                 23.0.0          py310hecd8cb5_0    defaults
pyqt                      5.15.7          py310he9d5cce_0    defaults
pyqt5-sip                 12.11.0                  pypi_0    pypi
pyrsistent                0.18.0          py310hca72f7f_0    defaults
pysocks                   1.7.1           py310hecd8cb5_0    defaults
python                    3.10.9               h218abb5_1    defaults
python-dateutil           2.8.2              pyhd3eb1b0_0    defaults
python-fastjsonschema     2.16.2          py310hecd8cb5_0    defaults
python-libarchive-c       2.9                pyhd3eb1b0_1    defaults
python.app                3               py310hca72f7f_0    defaults
python_abi                3.10                    2_cp310    conda-forge
pytz                      2022.7          py310hecd8cb5_0    defaults
pyyaml                    6.0             py310h6c40b1e_1    defaults
qt-main                   5.15.2               h719ae48_7    defaults
qt-webengine              5.15.9               h90a370e_4    defaults
qtpy                      2.2.0           py310hecd8cb5_0    defaults
qtwebkit                  5.212                h24dc246_4    defaults
readline                  8.2                  hca72f7f_0    defaults
reproc                    14.2.4               he9d5cce_1    defaults
reproc-cpp                14.2.4               he9d5cce_1    defaults
requests                  2.28.1          py310hecd8cb5_1    defaults
ripgrep                   13.0.0               hc2228c6_0    defaults
ruamel.yaml               0.17.21         py310hca72f7f_0    defaults
ruamel.yaml.clib          0.2.6           py310hca72f7f_1    defaults
ruamel_yaml               0.17.21         py310hca72f7f_0    defaults
setuptools                65.6.3          py310hecd8cb5_0    defaults
sip                       6.6.2           py310he9d5cce_0    defaults
six                       1.16.0             pyhd3eb1b0_1    defaults
soupsieve                 2.3.2.post1     py310hecd8cb5_0    defaults
sqlite                    3.41.1               h6c40b1e_0    defaults
tapi                      1000.10.8            ha1b3eb9_0    defaults
tk                        8.6.12               h5d9f67b_0    defaults
toml                      0.10.2             pyhd3eb1b0_0    defaults
tomli                     2.0.1           py310hecd8cb5_0    defaults
toolz                     0.12.0          py310hecd8cb5_0    defaults
tornado                   6.2             py310hca72f7f_0    defaults
tqdm                      4.65.0          py310h20db666_0    defaults
traitlets                 5.7.1           py310hecd8cb5_0    defaults
tzdata                    2022g                h04d1e81_0    defaults
ujson                     5.4.0           py310he9d5cce_0    defaults
urllib3                   1.26.14         py310hecd8cb5_0    defaults
wheel                     0.38.4          py310hecd8cb5_0    defaults
xz                        5.2.10               h6c40b1e_1    defaults
yaml                      0.2.5                haf1e3a3_0    defaults
yaml-cpp                  0.7.0                he9d5cce_1    defaults
zlib                      1.2.13               h4dc903c_0    defaults
zstandard                 0.19.0          py310h6c40b1e_0    defaults
zstd                      1.5.4                hc035e20_0    defaults
```

### Additional Context

Tried to install `mamba`, having its own problems:

% mamba
Traceback (most recent call last):
  File "/fw/m3cyue/Darwin/apps/anaconda3/condabin/mamba", line 7, in <module>
    from mamba.mamba import main
  File "/fw/m3cyue/Darwin/apps/anaconda3/lib/python3.10/site-packages/mamba/mamba.py", line 49, in <module>
    import libmambapy as api
  File "/fw/m3cyue/Darwin/apps/anaconda3/lib/python3.10/site-packages/libmambapy/__init__.py", line 7, in <module>
    raise e
  File "/fw/m3cyue/Darwin/apps/anaconda3/lib/python3.10/site-packages/libmambapy/__init__.py", line 4, in <module>
    from libmambapy.bindings import *  # noqa: F401,F403
ImportError: dlopen(/fw/m3cyue/Darwin/apps/anaconda3/lib/python3.10/site-packages/libmambapy/bindings.cpython-310-darwin.so, 0x0002): Library not loaded: '@rpath/libarchive.13.dylib'
  Referenced from: '/fw/m3cyue/Darwin/apps/anaconda3/lib/libmamba.2.0.0.dylib'
  Reason: tried: '/fw/m3cyue/Darwin/apps/anaconda3/lib/libarchive.13.dylib' (no such file), '/fw/m3cyue/Darwin/apps/anaconda3/lib/python3.10/site-packages/libmambapy/../../../libarchive.13.dylib' (no such file), '/fw/m3cyue/Darwin/apps/anaconda3/lib/python3.10/site-packages/libmambapy/../../../libarchive.13.dylib' (no such file), '/fw/m3cyue/Darwin/apps/anaconda3/bin/../lib/libarchive.13.dylib' (no such file), '/fw/m3cyue/Darwin/apps/anaconda3/bin/../lib/libarchive.13.dylib' (no such file), '/usr/local/lib/libarchive.13.dylib' (no such file), '/usr/lib/libarchive.13.dylib' (no such file)

**Comment by complyue** [comment]
Looking forward to the new release. Please feel free to close this whenever appropriate.

**Comment by jaimergp** [comment]
I'll leave it open for visibility. Please watch #168 to follow the release progress! Thanks! 🙏

**Comment by complyue** [comment]
Since #168 is done now, is Anaconda 2023.03-0 supposed to work now?

**Comment by complyue** [comment]
Now `conda-libmamba-solver` installs okay! But can't function :(

> CondaValueError: You have chosen a non-default solver backend (libmamba) but it was not recognized. Choose one of: classic

Should I open another issue for it?

Full transcript:
(note I've used `--only-deps anaconda` or it'll mysteriously remove `curl`)

```log
% conda install --only-deps anaconda conda-libmamba-solver
Collecting package metadata (current_repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: /fw/m3cyue/Darwin/apps/anaconda3

  added / updated specs:
    - _anaconda_depends
    - anaconda
    - boltons[version='>=23.0.0']
    - conda-libmamba-solver
    - libmambapy[version='>=1.4.1']


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    _anaconda_depends-2023.03  |          py310_0          67 KB  defaults
    boltons-23.0.0             |  py310hecd8cb5_0         426 KB  defaults
    conda-23.3.1               |  py310hecd8cb5_0         973 KB  defaults
    curl-7.88.1                |       h6c40b1e_0          84 KB  defaults
    fmt-9.1.0                  |       ha357a0b_0         186 KB  defaults
    jsonpatch-1.32             |     pyhd3eb1b0_0          15 KB  defaults
    jsonpointer-2.1            |     pyhd3eb1b0_0           9 KB  defaults
    libcurl-7.88.1             |       ha585b31_0         348 KB  defaults
    libmamba-1.4.1             |       ha357a0b_0         1.3 MB  defaults
    libmambapy-1.4.1           |  py310ha357a0b_0         255 KB  defaults
    libsolv-0.7.22             |       h8346a28_0         397 KB  defaults
    pcre2-10.37                |       he7042d7_1         823 KB  defaults
    pybind11-abi-4             |       hd3eb1b0_0          13 KB  defaults
    reproc-14.2.4              |       he9d5cce_1          27 KB  defaults
    reproc-cpp-14.2.4          |       he9d5cce_1          19 KB  defaults
    yaml-cpp-0.7.0             |       he9d5cce_1         442 KB  defaults
    zstd-1.5.4                 |       hc035e20_0         591 KB  defaults
    ------------------------------------------------------------
                                           Total:         5.8 MB

The following NEW packages will be INSTALLED:

  _anaconda_depends  pkgs/main/osx-64::_anaconda_depends-2023.03-py310_0 
  boltons            pkgs/main/osx-64::boltons-23.0.0-py310hecd8cb5_0 
  fmt                pkgs/main/osx-64::fmt-9.1.0-ha357a0b_0 
  jsonpatch          pkgs/main/noarch::jsonpatch-1.32-pyhd3eb1b0_0 
  jsonpointer        pkgs/main/noarch::jsonpointer-2.1-pyhd3eb1b0_0 
  libmamba           pkgs/main/osx-64::libmamba-1.4.1-ha357a0b_0 
  libmambapy         pkgs/main/osx-64::libmambapy-1.4.1-py310ha357a0b_0 
  libsolv            pkgs/main/osx-64::libsolv-0.7.22-h8346a28_0 
  pcre2              pkgs/main/osx-64::pcre2-10.37-he7042d7_1 
  pybind11-abi       pkgs/main/noarch::pybind11-abi-4-hd3eb1b0_0 
  reproc             pkgs/main/osx-64::reproc-14.2.4-he9d5cce_1 
  reproc-cpp         pkgs/main/osx-64::reproc-cpp-14.2.4-he9d5cce_1 
  yaml-cpp           pkgs/main/osx-64::yaml-cpp-0.7.0-he9d5cce_1 

The following packages will be UPDATED:

  conda                              23.1.0-py310hecd8cb5_0 --> 23.3.1-py310hecd8cb5_0 
  curl                                    7.87.0-h6c40b1e_0 --> 7.88.1-h6c40b1e_0 
  libcurl                                 7.87.0-ha585b31_0 --> 7.88.1-ha585b31_0 
  zstd                                     1.5.2-hcb37349_0 --> 1.5.4-hc035e20_0 


Proceed ([y]/n)? 


Downloading and Extracting Packages
                                                                                                                                                                                                                                                              
Preparing transaction: done                                                                                                                                                                                                                                   
Verifying transaction: done                                                                                                                                                                                                                                   
Executing transaction: done                                                                                                                                                                                                                                   
% 
% 
% conda config --set solver libmamba
% 
% conda install aiohttp

CondaValueError: You have chosen a non-default solver backend (libmamba) but it was not recognized. Choose one of: classic

% 
```

**Comment by jaimergp** [comment]
Thanks for the tip! Closing this as solved. 🙏
