### ISSUE TITLE
Still experimental?

### ISSUE THREAD

**Issue by jakirkham** [conda/conda-libmamba-solver#188]
Currently [the README notes the `conda-libmamba-solver` is still experimental]( https://github.com/conda/conda-libmamba-solver/blame/main/README.md#L12 ). As it has been out for a while now and received a fair bit of testing, am wondering if we would be comfortable dropping the experimental label? Or if we are not ready to do that, what still needs to happen before relaxing that term?

**Comment by jezdez** [comment]
Yeah, this is purely an oversight in the README and can be fixed. The package is not experimental anymore, even though there are a few issues still related to updating, we believe these are well understood and can be fixed in upcoming releases.

**Comment by jakirkham** [comment]
Thanks Jannis! 🙏

Am happy to add PRs anywhere we still find this text (starting with here)

**Comment by jakirkham** [comment]
Submitted PR ( https://github.com/conda/conda-libmamba-solver/pull/189 )

**Comment by jaimergp** [comment]
Thanks John!
