### ISSUE TITLE
Could not load conda plugin `conda-libmamba-solver`

### ISSUE THREAD

**Issue by qbxiaonb** [conda/conda-libmamba-solver#244]
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### What happened?

Dear community, 

I'm running into the following issue and tried to solve it on my own, but with no success. 
After installing the new conda-libmamba-solver from [(https://www.anaconda.com/blog/conda-is-fast-now)] into my base environment on an Intel Mac, I set the new solver as default using "conda config --set solver libmamba". 
However, I got the following error message: 

Could not load conda plugin `conda-libmamba-solver`:

dlopen(/opt/anaconda3/lib/python3.8/site-packages/libmambapy/bindings.cpython-38-darwin.so, 0x0002): Library not loaded: @rpath/libarchive.13.dylib
  Referenced from: <076ECB5C-F72E-3262-85B7-5A6BCF91985A> /opt/anaconda3/lib/libmamba.2.0.0.dylib
  Reason: tried: '/opt/anaconda3/lib/libarchive.13.dylib' (no such file), '/opt/anaconda3/lib/python3.8/site-packages/libmambapy/../../../libarchive.13.dylib' (no such file), '/opt/anaconda3/lib/python3.8/site-packages/libmambapy/../../../libarchive.13.dylib' (no such file), '/opt/anaconda3/bin/../lib/libarchive.13.dylib' (no such file), '/opt/anaconda3/bin/../lib/libarchive.13.dylib' (no such file), '/usr/local/lib/libarchive.13.dylib' (no such file), '/usr/lib/libarchive.13.dylib' (no such file, not in dyld cache)

I tried to uninstall conda-libmamba-solver, but it's outputting the same error message. Not sure what to do here to make it disappear. Your help is kindly appreciated! 

### Additional Context

**Comment by jaimergp** [comment]
Ensure libmamba, libmambapy and libarchive come from the same channel (use the classic solver to do so if needed), and then try again. Thanks!

**Comment by qbxiaonb** [comment]
Hi, thank you very much for your response. Do you mind sharing the code to do the above as I'm a newbie to Termninal?

**Comment by qbxiaonb** [comment]
With Conda-list in my base environment, I got:
conda-libmamba-solver     23.5.0             pyhd8ed1ab_0    conda-forge
libarchive                3.6.2                h65c5294_0  
libmamba                  1.4.9                hc2ec11d_0    conda-forge
libmambapy                1.4.9            py38hc40527a_0    conda-forge

However, with Conda search libarchive, I got loads of libarchive packages installed in the Conda-forge channel
# Name                       Version           Build  Channel             
libarchive                     3.2.1               1  conda-forge         
libarchive                     3.2.1               2  conda-forge         
libarchive                     3.3.2               0  conda-forge         
libarchive                     3.3.2      h823be47_0  conda-forge         
libarchive                     3.3.3   h02796b4_1008  conda-forge         
libarchive                     3.3.3   h46c8594_1004  conda-forge         
libarchive                     3.3.3   h5c473cc_1005  conda-forge         
libarchive                     3.3.3   h5c473cc_1006  conda-forge         
libarchive                     3.3.3   h5ee49f8_1001  conda-forge         
libarchive                     3.3.3   h5ee49f8_1002  conda-forge         
libarchive                     3.3.3      h823be47_0  conda-forge         
libarchive                     3.3.3   h8912c15_1007  conda-forge         
libarchive                     3.3.3   hb60c381_1000  conda-forge         
libarchive                     3.3.3      hc9f1ff1_2  conda-forge         
libarchive                     3.3.3   heb9f7fe_1003  conda-forge         
libarchive                     3.3.3   hf12134e_1008  conda-forge         
libarchive                     3.4.3      hf12134e_0  conda-forge         
libarchive                     3.5.0      hcf98e8c_0  conda-forge         
libarchive                     3.5.1      h078526d_0  conda-forge         
libarchive                     3.5.1      h0a5793d_1  conda-forge         
libarchive                     3.5.1      h2b60450_2  conda-forge         
libarchive                     3.5.2      h1a4c773_1  conda-forge         
libarchive                     3.5.2      h2b60450_0  conda-forge         
libarchive                     3.5.2      h2b60450_1  conda-forge         
libarchive                     3.5.2      hbf7dfe4_2  conda-forge         
libarchive                     3.5.2      hbf7dfe4_3  conda-forge         
libarchive                     3.5.2      hde4784d_2  conda-forge         
libarchive                     3.5.2      hde4784d_3  conda-forge         
libarchive                     3.6.1      h6d8d9f1_0  conda-forge         
libarchive                     3.6.1      h7181a6f_0  conda-forge         
libarchive                     3.6.2      h0b5dc4a_1  conda-forge         
libarchive                     3.6.2      h6d8d9f1_0  conda-forge         
libarchive                     3.6.2      h7181a6f_0  conda-forge

**Comment by jaimergp** [comment]
Try this:

```
$ conda install -n base conda-forge::libarchive --solver=classic
```

**Comment by ian-coccimiglio** [comment]
I had the same issue on M1 Mac. I solved it by removing libmamba, then reinstalling explicitly through the conda-forge channel, finally reinstalling the conda-libmamba-solver and setting it as the default solver.

```
conda remove libarchive
conda install libarchive -n base -c conda-forge
conda install -n base conda-libmamba-solver --solver=classic
conda config --set solver libmamba
```

Related details/solve show up here:
https://github.com/mamba-org/mamba/issues/1826

**Comment by jezdez** [comment]
I think we need to figure out a way to constrain these packages somehow, so they don't end up breaking people's env this way. @chenghlee @kenodegard @beeankha Do you have ideas how to do that?

**Comment by jaimergp** [comment]
There's no mechanism to request specific channels in conda-build, so all we can do is fix the underlying problem (see libarchive PR linked above), or bundle a static library with everything 😂

**Comment by jaimergp** [comment]
Added to #283, closing this to have a canonical source.
