### ISSUE TITLE
Doc URLs not working after theme switch

### ISSUE THREAD

**Issue by jezdez** [conda/conda-libmamba-solver#374]
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### What happened?

Two people reached out to me asking why the documentation for the project don't work, the links from Google lead to 404s.

I googled "conda-libmamba-solver" and it redirected to a non-existent page https://conda.github.io/conda-libmamba-solver/libmamba-vs-classic/user-guide/libmamba-vs-classic. This reads like the redirect setup didn't work, maybe it needed just a "slash" prefix.

**Comment by jaimergp** [comment]
Working now.
