### ISSUE TITLE
rules.c  solver_addrule: Assertion !p2 && d > 0 failed

### ISSUE THREAD

**Issue by andr0s** [conda/conda-libmamba-solver#387]
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### What happened?

a few dozen of packages, dockerfile.

Always crashing with error: rules.c  solver_addrule: Assertion !p2 && d > 0 failed.

Conda installed as:

RUN conda install -n base conda-libmamba-solver && \
    conda config --set solver libmamba

**Comment by jaimergp** [comment]
Hey @andr0s, thanks for the report!

Would you be able to share your Dockerfile contents (redact as necessary). I'm mostly interested in which conda packages you are trying to install using the libmamba solver. If possible, it would also help you have verbose logs attached. You can enable those with the `-vvv` flag.

With that info I can try get a reproducer and take a deeper look at the issue. Thanks!

**Comment by andr0s** [comment]
@jaimergp I found the problem :) It was because I had one package in the requirements.txt in a form of `libname>=1.2.3`, i.e. it had the version specified. Because it was a pip requirements file. After I removed the version (and `>=` obviously), things worked just fine

**Comment by jaimergp** [comment]
Interesting! That's supposed to work too 😂 You should have obtained a "package not found error" if anything, but definitely not a hard crash. Was it using a weird operator or was it really `>=`? I don't get it otherwise, but hey, happy you found a solution!
