### ISSUE TITLE
.solv files not being reused

### ISSUE THREAD

**Issue by tl-hbk** [conda/conda-libmamba-solver#481]
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### What happened?

It looks like in the following commit https://github.com/conda/conda-libmamba-solver/commit/8d9d6c03fd13e6a86a16fc396e1f7413baa269ea

a `try_solv` argument was added to `_json_path_to_repo_info` which defaults to `False`.  

From what I can tell this was added so that `reload_local_channels` could invalidate the `.solv` files but only other call to `_json_path_to_repo_info` in `_load_channels` did not get updated to use `try_solv=True`.  

This is causing every solve attempt to parse the repodata json and regenerate the `.solv` files even when all the channels are cache hits.  This leads to a performance hit.

**Comment by jaimergp** [comment]
Oh, excellent catch and just in time for a release, I'd say.
