### ISSUE TITLE
The conda-libmamba-solver documentation seems out-of-date (now that mamba is the default solver)?

### ISSUE THREAD

**Issue by jypeter** [conda/conda-libmamba-solver#516]
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### What happened?

I have read the [conda-libmamba-solver main User's guide page](https://conda.github.io/conda-libmamba-solver/user-guide/), and **it feels really weird and confusing, [now that libmamba is the default solver](https://conda.org/blog/2023-07-05-conda-libmamba-solver-rollout/) in recent installations**

For instance, I have an up-to-date version of conda (and related packages): `24.7`
```
> conda list conda
# packages in environment at /home/share/unix_files/cdat/miniconda3_2024-03:
#
# Name                    Version                   Build  Channel
conda                     24.7.1          py312h7900ff3_0    conda-forge
conda-content-trust       0.2.0              pyhd8ed1ab_0    conda-forge
conda-libmamba-solver     24.7.0             pyhd8ed1ab_0    conda-forge
conda-package-handling    2.3.0              pyh7900ff3_0    conda-forge
conda-package-streaming   0.10.0             pyhd8ed1ab_0    conda-forge
conda-which               0.2.0              pyhd8ed1ab_0    conda-forge
```
And limamba is the default solver since `conda 23.9`

Yet the user's guide seems to be written for people who still use old versions (e.g. [Update from the experimental versions (22.9 and below)](https://conda.github.io/conda-libmamba-solver/user-guide/#update-from-the-experimental-versions-22-9-and-below))

And the tip at the bottom of the page (_If you are unsure what configuration is being used by conda, you can inspect it with `conda config --show-sources`_) make no sense for users having a recent version. In my case, I get
```
 > conda config --show-sources
==> /home/users/jypeter/.condarc <==
channel_priority: strict
channels:
  - conda-forge
  - defaults
```
I have to use `conda info` or `conda config --show` if I want to get the solver information
```
> conda info | grep solver
                 solver : libmamba (default)
             user-agent : conda/24.7.1 requests/2.32.3 CPython/3.12.3 Linux/3.10.0-1160.108.1.el7.x86_64 centos/7.9.2009 glibc/2.17 solver/libmamba conda-libmamba-solver/24.7.0 libmambapy/1.5.8

> conda config --show | \grep solver
sat_solver: pycosat
solver: libmamba
solver_ignore_timestamps: False
```

Maybe the page should have different sections, based on the conda version? Or dealing with older versions should go to the FAQ ?
- if you have **conda >= 23.9**
- if you have **22.11 (?) <= conda < 23.9**
- if you have very old versions of conda (**conda <= 22.11** ?) : just install `mamba` directly and use it as a replacement of `conda`. I maintain a legacy installation based on conda 4.9.2 where I hase succesfully used `mamba` for a long time

**Comment by jaimergp** [comment]
Thanks, yes, this suggestion is spot on. I'll push a PR shortly.
