### ISSUE TITLE
Graduate conda-libmamba-solver to main conda organization

### ISSUE THREAD

**Issue by jezdez** [conda/conda-libmamba-solver#56]
In preparation of conda-libmamba-solver [losing the `experimental` label](https://github.com/conda-incubator/conda-libmamba-solver/pull/53) in the next release and getting [integration with the upcoming conda plugin system](https://github.com/conda/conda/pull/11993), **I would like to graduate conda-libmamba-solver to the main conda organization.**

We already have a capable team of maintainers between @wolfv, @jaimergp and me and hopefully more in the future from the larger conda ecosystem.

**Comment by beckermr** [comment]
yes

**Comment by xhochy** [comment]
yes

**Comment by ocefpaf** [comment]
yes

**Comment by kkraus14** [comment]
yes

**Comment by ericdill** [comment]
yes

**Comment by marcelotrevisani** [comment]
yes

**Comment by goanpeca** [comment]
Yes

**Comment by jakirkham** [comment]
Yes!

**Comment by jaimergp** [comment]
Yes

**Comment by wolfv** [comment]
Yes

**Comment by mbargull** [comment]
yes

**Comment by mariusvniekerk** [comment]
yes

**Comment by jezdez** [comment]
## Voting Results

This was a standard, non-timed-out vote.

Among [Steering Council members](https://github.com/conda-incubator/governance/blob/eaf59a5779dc1f678bee4453ceb92fd733e7306a/steering.csv) there are 14 "yes", 0 "no", and no abstentions.

This vote **has reached quorum** (14 is at least 60% of 16).

It **has also passed** since it recorded 14 "yes" votes and 0 "no" votes giving 14/14 which is greater than 60% of 16.

**Comment by jezdez** [comment]
The repo has been moved to the main conda organization and a new conda-libmamba-team community has been established: https://github.com/conda/conda-libmamba-solver 🥳

@wolfv Please see the invitation from GitHub to the newly created GitHub team in the conda org.
