### ISSUE TITLE
Switch to `conda` internals for all repodata fetching

### ISSUE THREAD

**Issue by jaimergp** [conda/conda-libmamba-solver#59]
Right now we use a mix of `libmamba` and `conda` objects to fetch the repodata, depending on the channel type. The initial reason behind this choice was that libmamba downloaded JSONs in parallel. However, thanks to @dholth's work on JLAP and parallel downloads with `conda`, we don't need that now and we can simplify it. From the testing perspective, it's also a reduction in complexity.

Fortunately, the implementation is just one `if` away, so we can make it happen for this release. The previous approach can be left as deprecated for a couple releases, guarded with an environment variable or something.

- [ ] #135
- [ ] #94

**Comment by dholth** [comment]
Can you link to that line?

**Comment by jaimergp** [comment]
Yes, sorry!

https://github.com/conda-incubator/conda-libmamba-solver/blob/main/conda_libmamba_solver/index.py#L218

**Comment by jezdez** [comment]
I've made this an epic, so we can start on #94 already, which may require updates to the libmamba API upstream.
