### ISSUE TITLE
libsolv solver prefers arch over build number

### ISSUE THREAD

**Issue by FFY00** [conda/conda-libmamba-solver#74]
### Checklist

- [X] I added a descriptive title
- [X] I searched for other issues and couldn't find a solution or duplication
- [X] I already searched in Google and didn't find any good information or help
- [X] I looked at the [docs](https://docs.conda.io/projects/conda/en/latest/user-guide/index.html) and didn't see anything to help

### What happened?

```python
    def test_noarch_preferred_over_arch_when_build_greater(self, env):
        env.repo_packages += [
            helpers.record(
                name='package1',
                build_number=0,
            ),
            helpers.record(
                name='package1',
                build_number=1,
                subdir='noarch',
            ),
        ]
        records = env.install('package1', container='original')
        assert len(records) == 1
        assert records[0].subdir == 'noarch'

```

```
Traceback (most recent call last):
  File "/home/anubis/git/conda/tests/test_solvers.py", line 1130, in test_noarch_preferred_over_arch_when_build_greater
    assert records[0].subdir == 'noarch'
AssertionError: assert 'linux-64' == 'noarch'
  - noarch
  + linux-64
```

It seems like the libsolv solver is picking `package1-1.0-0` over `package1-1.0-1` because `-0` has the `linux-64` subdir. The legacy solver prefers `-1` regardless of the arch, and has a test to make sure of this behavior.

cc @jaimergp

**Comment by jezdez** [comment]
Yep, this is the place: https://github.com/conda/conda-libmamba-solver/blob/568fbd84ec0976b2492c51794867fa7441792390/conda_libmamba_solver/mamba_utils.py#L138-L145
