### ISSUE TITLE
Setting default solver in Documentation: Getting Started not working.

### ISSUE THREAD

**Issue by LordKobra** [conda/conda-libmamba-solver#89]
Hello,

using conda version 22.9.0 i tried to install it following 
https://conda.github.io/conda-libmamba-solver/getting-started/

The command
`$ conda config --set solver libmamba`

throws the error:
`CondaValueError: Key 'solver' is not a known primitive parameter.`

I got it to work with
`$ conda config --set experimental_solver libmamba`

Best regards!

**Comment by jaimergp** [comment]
These are the docs for `conda=22.11` so you need to upgrade first. We'll add a clarification note, thanks!

**Comment by LordKobra** [comment]
Okay, thank you for clarification! From my side, the issue can be closed.

**Comment by jaimergp** [comment]
Thanks! It will be closed automatically once https://github.com/conda/conda-libmamba-solver/pull/93 is merged.
